name: Deploy to Staging

on:
  push:
    branches:
      - main  # Cambia esto a la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -p 65002 ${{ secrets.STAGING_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        # Definir variables
        STAGING_USER=${{ secrets.STAGING_USER }}
        STAGING_SERVER_IP=${{ secrets.STAGING_SERVER_IP }} 
        STAGING_PATH=${{ secrets.STAGING_PATH }}
    
        # Conectar al servidor de staging y desplegar el código usando el puerto 65002
        rsync -avz --exclude='.git*' -e "ssh -p 65002" ./ $STAGING_USER@$STAGING_SERVER_IP:$STAGING_PATH

 